### ISSUE TITLE
Changes to memory allocation prevent server startup

### ISSUE THREAD

**Issue by tgoodyear** [robmccoll/stinger#127]
As of PR #122 `stinger_server` is unable to start using either reduced or default cmake values. Error received: `FATAL: stinger_shared.c X: Bus Error - writing to STINGER failed.  It is likely that your STINGER is too large.`

Replicated on clean builds in two environments: Ubuntu 14.04.3
 * 64GB / 32GB RAM
 * E5-2650 v2 / i7-3770

`/dev/shm/stinger-default` is created and not deleted on crash.

**Comment by davidediger** [comment]
@sirpoovey I would assign this to you if it would let me.

**Comment by tgoodyear** [comment]
This is resolved
