### ISSUE TITLE
Example in README needs to be modified

### ISSUE THREAD

**Issue by ogreen** [robmccoll/stinger#54]
The current example is as follows:
term1:build$ rmat_graph_generator -s 18 -e 8
term1:build$ insert_remove_benchmark -n 1 -b 100000 g.18.8.bin a.18.8.100000.bin

This does not generate the actions file. A "-n 100000" should be added.

**Comment by davidediger** [comment]
@ogreen, are you interested in submitting a pull request or should I update it myself?

**Comment by ogreen** [comment]
@davidediger, sure I will take care of it.

**Comment by davidediger** [comment]
Thanks @ogreen.  Glad to have you as a contributor.
