### ISSUE TITLE
Poorly formatted JSON request crashes server

### ISSUE THREAD

**Issue by sirpoovey** [robmccoll/stinger#62]
The following command crashes JSON RPC server

curl -XPOST localhost:8088/jsonrpc -d "{"jsonrpc": "2.0", "method": "get_algorithms", "id": 1}"

**Comment by davidediger** [comment]
We need to figure out how this is different from #34 which is fixed on the dev branch.

**Comment by davidediger** [comment]
As of this moment, this command no longer crashes the server.  Instead, it throws an Invalid Request error object back.  Closing.
