### ISSUE TITLE
Possible bug in static connected component

### ISSUE THREAD

**Issue by odedgreen** [robmccoll/stinger#63]
In file https://github.com/robmccoll/stinger/blob/master/src/bin/standalone/connected_components/connected-comp.c,
Line 461 is as follows:
    MTA ("mta assert nodep");

Seems like that semicolon should not be there, not familiar enough Cray macros

**Comment by davidediger** [comment]
Yes that's definitely a typo.  Can't remember if it affects the Cray compiler or not.  I'll go ahead and fix, even though I doubt STINGER is ever going to run on the XMT again.  Thanks, @odedgreen!
