### ISSUE TITLE
Cannot compile on mac (fix included).

### ISSUE THREAD

**Issue by kikohs** [robmccoll/stinger#66]
Hello,

I found an issue in server.cpp which prevents to compile the project on mac (10.10.3) using clang.

The function **kill** needs a pid a not a pthread_t object. Using the following code seems to fix the problem as it compiles and the server stops as expected.

In server.cpp

    #include <sys/syscall.h>

Around line 200:

    pid_t tid;
    tid = syscall(SYS_gettid);
    // kill(name_pid, SIGTERM);
    pthread_kill(name_pid, SIGTERM);
    // kill(tid, SIGTERM);
    waitpid(tid, &status, 0);
    printf(" done.\n"); fflush(stdout);

    printf("Shutting down the batch server..."); fflush(stdout);

    pthread_kill(batch_pid, SIGTERM);
    // kill(batch_pid, SIGTERM);
    // waitpid(batch_pid, &status, 0);
    waitpid(tid, &status, 0);
    printf(" done.\n"); fflush(stdout);

**Comment by davidediger** [comment]
Nice catch, @kikohs.  If you want credit for the fix, we'll take a pull request on the dev branch.  Otherwise I'd be happy to incorporate it for you.

**Comment by kikohs** [comment]
I don't need credits, please do :)
