### ISSUE TITLE
Adding huge number of vertices/edges in parallel?

### ISSUE THREAD

**Issue by kaatish** [robmccoll/stinger#73]
Hi,
I have a large file from another program which contains the information about an edge.
Each line contains a source vertex and a destination vertex. There is only one edge and one vertex type for this graph. Since an edge can appear more than once, I want the weight of the edge in the stinger graph to denote the number of times this edge has appeared in the file.

Right now, I have tried using an openmp for loop with stinger_mapping_create to create the vertices and stinger_incr_edge to create the edge, something like this:
```
#pragma omp parallel for
  for(int i = 0; i < num_data; i++)
  {
    int64_t sid, did;
    int s = stinger_mapping_create(graph, source.at(i).c_str(),
        source.at(i).length(), &sid);
    int d = stinger_mapping_create(graph, dest.at(i).c_str(),
        dest.at(i).length(), &did);
    int res = stinger_incr_edge(graph, 0, sid, did, 1, edge.at(i).time());
  }
```

I was expecting the sum of the weights of all the edges to be the same regardless of the number of openmp threads but this is not the case. I have been adding the weights like this:
```
  uint64_t weight = 0;
  for(int64_t t = 0; t < graph->max_netypes; t++)
  {
    STINGER_FORALL_EDGES_BEGIN(graph, t)
    {
      weight += STINGER_EDGE_WEIGHT;
    }
    STINGER_FORALL_EDGES_END();
  }
```
The number of vertices and edges in the final does remain the same regardless of the choice of threads, but I think this might be by chance.
So clearly stinger_incr_edges looks incompatible with openmp. Is there something that I am doing wrong that can be rectified to do parallel insertion of edges?

**Comment by jpfairbanks** [comment]
The model used by stinger is to make a batch of edges and insert them in parallel. To see this in action see the clients/streams directory there are examples for csv and json streams of edges. Much of the code is for making the whole thing work over a network but the core of the streams is that they insert batches of edges.

**Comment by jpfairbanks** [comment]
server/batch.cpp also deals with inserting the batches.

**Comment by davidediger** [comment]
At first glance, the code snippets you've provided look right.  There may very well be an issue with the edge weights in parallel.  We'll take a look at it.

**Comment by davidediger** [comment]
Looks to me like stinger_incr_edge() isn't protecting the weight update in a parallel-safe way.  The code appears to be copied from stinger_insert_edge(), but with an unsafe add.  I'd like to be able to fix this with an atomic-fetch-and-add on the weight field rather than locking the edge just to increment the weight.

**Comment by davidediger** [comment]
@kaatish , why don't you try to merge the hotfix-73 branch and see if that fixes your issue.  If you get consistent results with different numbers of threads, we'll fold that in.

**Comment by kaatish** [comment]
@davidediger I cloned the hotfix-73 branch. I was getting segmentation faults, so I removed the omp pragmas.

I have not tested this extensively but it seems that the stinger_incr_edge is currently giving seg faults when it tries to increment the weight after the first time an edge is created.

I gave a bunch of std::cerr's before vertex and edge insertion to debug the program. Initially, the second edge insertion was unsuccessful giving a set fault message. The input file had repeated first three edges. Upon removing the repeated edges, the program was successful in inserting the next edge after that. The repetition of the next edge though, did cause the program to experience seg fault again.

I will be testing things more, to check if I haven't made a mistake on my end.

**Comment by davidediger** [comment]
Again, not you, @kaatish .  Forgot to get the address of the edge weight in the fetch-and-add.  Compiler doesn't help you out there.  And I obviously did a very poor job testing before pushing.  Was trying to get this to you quickly.

I just pushed an update to the hotfix.  I tested it with a modified version of the insert_remove_benchmark.  Results look consistent with changing numbers of threads.  If you don't mind, we may adopt your weight summation for a future test case of the increment functionality.

**Comment by kaatish** [comment]
@davidediger I think it works now! The summation of the weights is turning out to be correct and I am not getting segfaults. Should I close this issue?

**Comment by kaatish** [comment]
Hi,
I just wanted to know when will this hotfix be merged to master.

**Comment by davidediger** [comment]
Just merged the hotfix with master and dev.
