### ISSUE TITLE
Streaming connected components to file

### ISSUE THREAD

**Issue by kikohs** [robmccoll/stinger#74]
Disclaimer: I am completely new to stinger.

Problem: I want to stream edges to stinger and dump connected components as soon as they are completed.

Could anyone point me in the right direction? The documentation on the website seems outdated and the applications in the bin folder are not commented.

Thank you

**Comment by davidediger** [comment]
A couple of quick questions:  1. where are your edges coming from?  2.  Do you want to dump connected components at the end after you've seen all the edges or every so often?

**Comment by kikohs** [comment]
My edges are generated from another program (graphlab) I can dump them to a file and stream them or directly stream them to a Stinger server.
I want to dump the component when all it is disconnected form the others, all its edges have been seen. I expect hundreds of thousands of components so I want to dump then as soon as possible to free memory.

**Comment by jpfairbanks** [comment]
Connected components takes only one word per vertex independent of the
number of components. So dumping them won't allow you to free that much
memory.

What is the degree distribution of the graph? Stinger has some design
decisions that optimize for social network data. If your data is very
different, then that might explain the  performance.

**Comment by kikohs** [comment]
I am not talking about performance. I didn't implement the system yet: I am looking for advice on how to do it. The graph will have thousands of components, I am not sure about their shape for now.

The process of streaming may run and never stop, I want to dump components regularly to analyse them while the new edges are fed to the system.

Any tips?

**Comment by jpfairbanks** [comment]
Yes we have been using a workflow that works for dynamic graph data. You
would have a batch of edges, compute the connected components, write out
the components, and then wait for another batch of edges. The client/server
protocol that is built into stinger allows you to implement this workflow.

The idea is that streams supply edges and algorithms compute things. the
server can handle the scheduling for you.

**Comment by davidediger** [comment]
@kikohs , there are several ways to send edges to the server.  You could use one of the included streams to process them from stdin, such as the CSV stream or JSON stream.  You could use the Python library to send them.  You could write your own code that implements the STINGER protobufs interface and send batches of edges over TCP.

If you start a Stinger server process and a connected components process, the Stinger server will calculate the connected components for each batch of edges you send.  Starting the server with the -k flag (I think) will write the component labels to disk at each time interval.  It's a rather raw format, so perhaps you'll want to write something more human-readable.

**Comment by kikohs** [comment]
Thanks for the tips. I'll try to implement that.
