### ISSUE TITLE
Multiple Edges between two vertices

### ISSUE THREAD

**Issue by kaatish** [robmccoll/stinger#75]
Hi,
I think having multiple edges between the same 2 vertices is not possible, yet. What parts of the source code should I look into, if I want to have this feature? In my use case, an edge between two vertices can be unique in terms of a few properties, which I could add to the struct stinger_edge found in stinger_internal.h.

Would updating/adding alternatives to all the functions in stinger.h wrt to edge modification do the trick or should I look elsewhere as well?

**Comment by davidediger** [comment]
Multiple edges between the same two vertices is possible if the edges are of different types.  We don't support multiple instances of the same edge of the same type (a traditional multigraph).  You could extend the stinger_edge struct, but you would also have to chance stinger_insert_edge(), stinger_incr_edge(), and stinger_delete_edge() to implement a new search criteria.

**Comment by sirpoovey** [comment]
David is correct.  If the edges are different types, that is supported.  If you need more than a few edge types, I have done some internal work to allow for "extended edge types" that allow for many edge types without exploding the memory space.  If this is of interest I could try cleaning that up and submitting it back.

**Comment by kaatish** [comment]
@sirpoovey I think that will be very useful for me. In my use case, it could be beneficial to have more than a few edge types.

**Comment by davidediger** [comment]
Just for the sake of understanding your problem, how many edge types do you think would be reasonable?

**Comment by kaatish** [comment]
It will probably be in the hundreds to begin with. How many edge types does the 'extended edge types' approach allow?

**Comment by sirpoovey** [comment]
There would be no enforced limits, just any edge type over the max_etypes
would share a single internal edge type.

Jason
