### ISSUE TITLE
Negative Edge Weight

### ISSUE THREAD

**Issue by kaatish** [robmccoll/stinger#77]
Hi,
Can stinger support negative edge weights?

**Comment by davidediger** [comment]
There is nothing in the data structure that precludes negative edge weights.  The field is an int64_t and the functions that assign/increment it don't really care.  It's possible that higher up the stack (I'm thinking about the protobuf batch of edges or the stream processors), there is an assumption that the weights are positive (or non-negative), but if there is, it probably isn't necessary.  If you find such a thing, let us know so we can fix it.
