### ISSUE TITLE
Vertex Creation without string value

### ISSUE THREAD

**Issue by kaatish** [robmccoll/stinger#86]
This is more of a question. Is it possible to create a vertex with an integer key (32 or 64 bit) rather than a string as in stinger_mapping_create()? If not, how can this be achieved?

Thing is, that in my use case, it makes sense to assign an integer to a vertex rather than a string. Currently, I have to convert integers to strings to be able to insert a vertex. If possible, I would prefer to avoid this.

**Comment by davidediger** [comment]
We've been discussing this in #33.  The easiest solution is to use the string representation of the integer.  You don't necessarily need to use the name physical mapper to allocate vertices.  You could do so yourself.

Also, there is a pending pull request that makes SQLite an option for the physical mapper.
