### ISSUE TITLE
Iterating through all vertices

### ISSUE THREAD

**Issue by kaatish** [robmccoll/stinger#87]
How can I iterate through all the vertices in a graph that have an edge without using bothering with the string to identify each vertex?

**Comment by davidediger** [comment]
Do the STINGER traversal macros work for you: src/lib/stinger_core/inc/stinger_traversal.h ?

Typically, we have an outer for loop that iterates through all logical vertex IDs 0 to |V|-1.  If the outdegree is greater than zero, than you use the STINGER_FORALL_EDGES_OF_VTX_BEGIN macro to iterate the neighbors of that vertex.

Does that make sense?

**Comment by kaatish** [comment]
That makes sense. So the `|V|` should be taken from `stinger_max_active_vertex`, right?

**Comment by davidediger** [comment]
That would work.   stinger_max_active_vertex() is a bit expensive, but will give you a tight bound.  stinger_max_nv() is cheap (just a lookup), but looks at all vertices.  That's the way I would do it.

**Comment by kaatish** [comment]
Thanks!
